// Base de données des véhicules populaires au Québec

export const vehicleMakes = [
  "Acura",
  "Audi",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jeep",
  "Kia",
  "Lexus",
  "Lincoln",
  "Mazda",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const vehicleModels: Record<string, string[]> = {
  Acura: ["ILX", "TLX", "RDX", "MDX", "Integra"],
  Audi: ["A3", "A4", "A5", "A6", "Q3", "Q5", "Q7", "e-tron"],
  BMW: ["Série 2", "Série 3", "Série 4", "Série 5", "X1", "X3", "X5", "iX"],
  Buick: ["Encore", "Encore GX", "Envision", "Enclave"],
  Cadillac: ["CT4", "CT5", "XT4", "XT5", "XT6", "Escalade", "Lyriq"],
  Chevrolet: [
    "Spark",
    "Cruze",
    "Malibu",
    "Camaro",
    "Corvette",
    "Trax",
    "Equinox",
    "Blazer",
    "Traverse",
    "Tahoe",
    "Suburban",
    "Colorado",
    "Silverado",
    "Bolt EV",
  ],
  Chrysler: ["300", "Pacifica", "Grand Caravan"],
  Dodge: ["Charger", "Challenger", "Durango", "Grand Caravan", "Journey"],
  Ford: [
    "Fiesta",
    "Focus",
    "Fusion",
    "Mustang",
    "EcoSport",
    "Escape",
    "Bronco",
    "Edge",
    "Explorer",
    "Expedition",
    "Ranger",
    "F-150",
    "F-250",
    "Maverick",
    "Mach-E",
  ],
  GMC: ["Terrain", "Acadia", "Yukon", "Canyon", "Sierra 1500", "Sierra 2500"],
  Honda: [
    "Civic",
    "Accord",
    "Insight",
    "HR-V",
    "CR-V",
    "Passport",
    "Pilot",
    "Odyssey",
    "Ridgeline",
  ],
  Hyundai: [
    "Accent",
    "Elantra",
    "Sonata",
    "Veloster",
    "Kona",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Ioniq 5",
    "Ioniq 6",
  ],
  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  Jeep: [
    "Renegade",
    "Compass",
    "Cherokee",
    "Grand Cherokee",
    "Wrangler",
    "Gladiator",
    "Wagoneer",
  ],
  Kia: [
    "Rio",
    "Forte",
    "K5",
    "Stinger",
    "Soul",
    "Seltos",
    "Sportage",
    "Sorento",
    "Telluride",
    "Carnival",
    "EV6",
    "Niro",
  ],
  Lexus: ["IS", "ES", "LS", "UX", "NX", "RX", "GX", "LX"],
  Lincoln: ["Corsair", "Nautilus", "Aviator", "Navigator"],
  Mazda: [
    "Mazda3",
    "Mazda6",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-9",
    "MX-5 Miata",
    "MX-30",
  ],
  "Mercedes-Benz": [
    "Classe A",
    "Classe C",
    "Classe E",
    "Classe S",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "EQB",
    "EQE",
    "EQS",
  ],
  Mini: ["Cooper", "Cooper S", "Countryman", "Clubman"],
  Mitsubishi: ["Mirage", "Eclipse Cross", "Outlander", "Outlander PHEV"],
  Nissan: [
    "Versa",
    "Sentra",
    "Altima",
    "Maxima",
    "Leaf",
    "Kicks",
    "Rogue",
    "Murano",
    "Pathfinder",
    "Armada",
    "Frontier",
    "Titan",
  ],
  Porsche: ["718", "911", "Taycan", "Macan", "Cayenne", "Panamera"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Subaru: [
    "Impreza",
    "Legacy",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Outback",
    "Ascent",
    "Solterra",
  ],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Toyota: [
    "Corolla",
    "Camry",
    "Avalon",
    "Prius",
    "GR86",
    "Supra",
    "C-HR",
    "RAV4",
    "Venza",
    "Highlander",
    "4Runner",
    "Sequoia",
    "Tacoma",
    "Tundra",
    "Sienna",
    "bZ4X",
  ],
  Volkswagen: [
    "Jetta",
    "Passat",
    "Arteon",
    "Golf",
    "GTI",
    "Golf R",
    "Taos",
    "Tiguan",
    "Atlas",
    "ID.4",
  ],
  Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40 Recharge"],
};

// Types de vitrage
export const glassTypes = [
  { id: "windshield", label: "Pare-brise avant", icon: "🚗" },
  { id: "rear", label: "Vitre arrière", icon: "🔙" },
  { id: "side-front-left", label: "Vitre latérale avant gauche", icon: "◀️" },
  { id: "side-front-right", label: "Vitre latérale avant droite", icon: "▶️" },
  { id: "side-rear-left", label: "Vitre latérale arrière gauche", icon: "◀️" },
  { id: "side-rear-right", label: "Vitre latérale arrière droite", icon: "▶️" },
  { id: "sunroof", label: "Toit ouvrant", icon: "☀️" },
];

// Codes postaux desservis (région de Montréal)
export const serviceAreas = [
  // Montréal
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H7",
  "H8",
  "H9",
  // Laval
  "H7A",
  "H7B",
  "H7C",
  "H7E",
  "H7G",
  "H7H",
  "H7K",
  "H7L",
  "H7M",
  "H7N",
  "H7P",
  "H7R",
  "H7S",
  "H7T",
  "H7V",
  "H7W",
  "H7X",
  "H7Y",
  // Rive-Sud
  "J3",
  "J4",
  "J5",
  // Rive-Nord
  "J6",
  "J7",
];

export function isPostalCodeServiced(postalCode: string): boolean {
  const normalized = postalCode.toUpperCase().replace(/\s/g, "");
  const prefix2 = normalized.substring(0, 2);
  const prefix3 = normalized.substring(0, 3);

  return serviceAreas.some(
    (area) =>
      area === prefix2 || area === prefix3 || normalized.startsWith(area)
  );
}

// Créneaux horaires disponibles
export const timeSlots = [
  { id: "08:00", label: "8h00 - 10h00", period: "matin" },
  { id: "10:00", label: "10h00 - 12h00", period: "matin" },
  { id: "12:00", label: "12h00 - 14h00", period: "midi" },
  { id: "14:00", label: "14h00 - 16h00", period: "apres-midi" },
  { id: "16:00", label: "16h00 - 18h00", period: "apres-midi" },
];

// Générer les années (de l'année actuelle jusqu'à 30 ans en arrière)
export function getYears(): number[] {
  const currentYear = new Date().getFullYear() + 1; // Include next year for new models
  return Array.from({ length: 32 }, (_, i) => currentYear - i);
}
